### ISSUE TITLE
add a possibility to change the class for which the schedule is retrieved

### ISSUE THREAD

**Issue by MrFincher** [reclaimingmytime/schedule#2]
This could be implemented with a get parameter. So that users from different classes then the server owner could still use the application. (for example by creating a bookmark which includes the class get parameter)

The default (if no get parameter is provided) could be set in the config file.

An option to set the class through the UI would also be desirable.

**Comment by reclaimingmytime** [comment]
Thanks for the suggestion.

I have now added the get parameter "c" as well as the variables `$defaultClass` and `$allowedClasses`. This sets a cookie internally so the setting is persistent across a refresh.

So, a bookmark should work (and should persist). Just the graphical frontend is missing.

**Comment by reclaimingmytime** [comment]
**Update**: A dropdown has now been implemented. The current dropdown is not responsive, so I have disabled it for mobile devices until a better solution is found.

In the meantime, if you're on mobile, you can simply hold your phone horizontally ("landscape mode) or visit `?c=DesiredClass`.

**Comment by reclaimingmytime** [comment]
**Update 2**: I have now added a dropdown at the bottom of the screen for mobile devices. As the dropdown is outside the navigation bar, it is fully responsive.
