### ISSUE TITLE
Swiping on mobile Safari not available on whitespace at the bottom

### ISSUE THREAD

**Issue by bramnijssen** [reclaimingmytime/schedule#3]
When having a small schedule for the day or don't have any lectures at all, most of the bottom half of the page is occupied by whitespace. However, you are not able to navigate through the schedule by swiping in this area on mobile Safari (only on the area that is occupied by text). Since most people don't have a long thumb that can reach the top of their screen when using the phone with one hand, this feature might come in handy... :sweat_smile:

**Comment by reclaimingmytime** [comment]
Thanks for reporting.

The issue has been solved in commit de449f8.
